<a href="https://colab.research.google.com/github/code130/hello-world/blob/master/SVM_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [2]:
from numpy.random import seed
from sklearn.preprocessing import minmax_scale
from sklearn.model_selection import train_test_split
from keras.layers import Input, Dense
from keras.models import Model
import pandas as pd
from numpy.random import seed
from sklearn.preprocessing import minmax_scale
GENOMICS_DATA_URL = '/content/drive/MyDrive/SSI Project/datasets/gene_expression/source/Breast_GSE70947.csv'
data_frame = pd.read_csv(GENOMICS_DATA_URL)


data_frame = data_frame.drop(columns="samples")
#display(data_frame)

In [3]:
y = data_frame['type']
display(y)

df_x = data_frame.iloc[:,2:].values
display(df_x)

0                     normal
1                     normal
2                     normal
3                     normal
4                     normal
               ...          
284    breast_adenocarcinoma
285    breast_adenocarcinoma
286    breast_adenocarcinoma
287    breast_adenocarcinoma
288    breast_adenocarcinoma
Name: type, Length: 289, dtype: object

array([[ 7.71801596,  6.04443769, 10.74707702, ...,  8.96943885,
         4.98569278,  5.09049955],
       [ 7.07223164,  6.97674149, 10.42967138, ...,  8.17448935,
         4.46417694,  4.53689133],
       [ 7.96457276,  6.26905517, 10.82502492, ...,  8.4734676 ,
         4.66844655,  5.08412743],
       ...,
       [ 7.65189288,  5.8456198 , 11.73525745, ...,  8.75907992,
         4.55673743,  4.62711686],
       [ 8.09668189,  6.35538709, 11.55609033, ...,  9.65815497,
         4.51579939,  4.5833562 ],
       [ 7.53889842,  6.36455742, 11.86137988, ...,  9.73935803,
         4.95241565,  4.77099256]])

In [4]:
df_x_scaled = minmax_scale(df_x, axis = 0)

In [5]:
# define the number of features
ncol = df_x_scaled.shape[1]
ncol

35980

In [6]:
X_train, X_test, Y_train, Y_test = train_test_split(df_x_scaled, y, train_size = 0.8, random_state = seed(2052))

In [7]:
from sklearn import svm
# define the model

#Create a svm Classifier
clf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, Y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)




In [8]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(Y_test, y_pred))
display(Y_test.shape)
y_pred.shape

Accuracy: 0.9655172413793104


(58,)

(58,)

In [9]:
from sklearn.metrics import confusion_matrix

In [10]:
prediction_train = clf.predict(X_train)
display(confusion_matrix(Y_train, prediction_train))

array([[118,   0],
       [  0, 113]])

In [11]:
prediction_test = clf.predict(X_test)
display(confusion_matrix(Y_test, prediction_test))

array([[24,  1],
       [ 1, 32]])